"""init

Revision ID: 3e9690a5792a
Revises: 
Create Date: 2026-05-08 11:44:47.719688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9690a5792a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_service_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supabase_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_service_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_service_users_supabase_id'), ['supabase_id'], unique=True)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'IN_USE', 'MAINTENANCE', 'RETIRED', name='assetstatus'), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_created_by'), ['created_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_created_by'))

    op.drop_table('assets')
    with op.batch_alter_table('asset_service_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_service_users_supertokens_id'))

    op.drop_table('asset_service_users')
    # ### end Alembic commands ###
